import type { Product } from "./types";

const RESEARCH_NOTICE =
  "For laboratory research purposes only. Not for human consumption. Not a medicine, supplement, or cosmetic. Intended for controlled laboratory and in vitro use only.";

const PRODUCT_DISCLAIMER =
  "This product and its description are intended solely for laboratory and controlled research use. Nothing on this page is medical advice, dosing guidance, or an invitation for personal use. Not for human consumption.";

const commonFaqs = (name: string): Product["faqs"] => [
  {
    question: "Is this lab tested?",
    answer:
      "Listed batches are assessed for purity and identity, with Certificates of Analysis available on request for verified lots.",
  },
  {
    question: "How fast is Australian delivery?",
    answer:
      "Express Australia Post typically runs 1 to 3 business days after dispatch, depending on destination.",
  },
  {
    question: "Is outer packaging discreet?",
    answer:
      "Yes. Outer cartons use plain labelling without product descriptors.",
  },
  {
    question: `What is ${name} supplied for?`,
    answer:
      "Research inventory only. It is not for human or veterinary use, therapeutic procedures, or consumer applications.",
  },
];

export const products: Product[] = [
  {
    slug: "bacteriostatic-water-10ml",
    name: "Bacteriostatic Water (10mL)",
    shortName: "Bacteriostatic Water",
    strength: "10mL",
    priceAud: 19.99,
    categorySlugs: ["research-solvents"],
    shortLabel: "Sterile research solvent | 0.9% benzyl alcohol | 10mL vial",
    metaTitle: "Bacteriostatic Water 10mL Australia | Peptide Protocol",
    metaDescription:
      "Buy bacteriostatic water 10mL for research reconstitution in Australia. Sterile water with 0.9% benzyl alcohol. Research use only.",
    headline: "Bacteriostatic water for laboratory reconstitution protocols",
    body: [
      "Bacteriostatic Water is sterile water for injection containing 0.9% benzyl alcohol as a bacteriostatic preservative. Peptide Protocol supplies 10mL vials for reconstitution of lyophilised research materials under trained laboratory procedures.",
      "Use only within controlled research settings and according to your organisation’s solvent handling SOPs. This product is a research reagent, not a consumer or clinical preparation.",
    ],
    researchNotice: RESEARCH_NOTICE,
    specs: [
      { label: "Composition", value: "Sterile water with 0.9% benzyl alcohol" },
      { label: "Volume", value: "10mL per vial" },
      { label: "Form", value: "Clear sterile liquid" },
      { label: "Intended use", value: "Research reconstitution solvent" },
      { label: "Quality checks", value: "As per batch documentation / COA where applicable" },
      { label: "Net content", value: "10mL" },
    ],
    storage: [
      "Store sealed at controlled room temperature unless batch documentation states otherwise.",
      "Protect from light and contamination after opening, per laboratory SOP.",
      "Do not use if the solution is cloudy, discoloured, or the seal is compromised.",
      "Dispose of according to your organisation’s chemical waste procedures.",
    ],
    included: [
      "1 × Bacteriostatic Water, 10mL sterile vial",
      "Protective inner packing",
      "Australia Post tracking after dispatch",
    ],
    qualitySignals: [
      "Sterile presentation for research reconstitution workflows",
      "Clear labelling for inventory control",
      "Tamper checks before dispatch",
    ],
    faqs: commonFaqs("Bacteriostatic Water"),
    disclaimer: PRODUCT_DISCLAIMER,
    image: "/images/products/bacteriostatic-water.jpg",
    promoLabel: "Often included free with qualifying catalogue orders",
    featured: true,
  },
  {
    slug: "bpc-157-10mg",
    name: "BPC-157 (10mg)",
    shortName: "BPC-157",
    strength: "10mg",
    priceAud: 69.99,
    categorySlugs: ["tissue-recovery"],
    shortLabel: "Pentadecapeptide | Research grade | Lyophilised powder",
    metaTitle: "BPC-157 10mg Research Peptide Australia | Peptide Protocol",
    metaDescription:
      "Buy BPC-157 10mg lyophilised research peptide in Australia. Specs, storage notes, and COA access. Research use only.",
    headline: "BPC-157 for controlled tissue and recovery research models",
    body: [
      "BPC-157 is a synthetic 15-amino-acid peptide sequence derived from a portion of body protection compound research literature. Peptide Protocol supplies this material as a lyophilised powder for in vitro and other controlled laboratory applications.",
      "Each batch is prepared for research inventory use, with purity assessed by RP-HPLC and a Certificate of Analysis available for verified lots.",
    ],
    researchNotice: RESEARCH_NOTICE,
    specs: [
      { label: "Synonyms", value: "Body Protection Compound-157, Bepecin (research literature)" },
      { label: "CAS number", value: "137525-51-0" },
      { label: "Chemical formula", value: "C62H98N16O22" },
      { label: "Molecular weight", value: "Approx. 1419.5 g/mol" },
      { label: "Peptide length", value: "15 amino acids" },
      { label: "Form", value: "White to off-white lyophilised powder" },
      { label: "Purity", value: "≥99.0% (COA validated)" },
      { label: "Solubility", value: "Soluble in sterile research solvents as per lab protocol" },
      { label: "Quality checks", value: "RP-HPLC identity/purity assessment; third-party verification where listed" },
      { label: "Net content", value: "10mg per vial" },
    ],
    storage: [
      "Store dry at 2–8°C unless your batch documentation states otherwise.",
      "Protect from moisture, light, and repeated temperature cycling.",
      "Reconstitute only under trained laboratory procedures using suitable sterile solvents.",
      "Follow your organisation’s SOPs for labelling, use, and disposal.",
    ],
    included: [
      "1 × BPC-157, 10mg lyophilised vial",
      "Protective inner packing",
      "Access to batch-specific COA where available",
      "Australia Post tracking after dispatch",
    ],
    qualitySignals: [
      "≥99% purity target with COA support",
      "Third-party laboratory verification on listed batches",
      "Tamper-evident packing checks before dispatch",
      "Clear product labelling for research inventory control",
    ],
    faqs: commonFaqs("BPC-157"),
    disclaimer: PRODUCT_DISCLAIMER,
    image: "/images/products/bpc-157.jpg",
    featured: true,
  },
  {
    slug: "cjc-1295-dac-5mg",
    name: "CJC-1295 with DAC (5mg)",
    shortName: "CJC-1295 DAC",
    strength: "5mg",
    priceAud: 74.99,
    categorySlugs: ["growth-hormone"],
    shortLabel: "GHRH analogue with DAC | Research grade | Lyophilised powder",
    metaTitle: "CJC-1295 DAC 5mg Research Peptide Australia | Peptide Protocol",
    metaDescription:
      "Buy CJC-1295 with DAC 5mg lyophilised research peptide in Australia. Specs, storage, COA access. Research use only.",
    headline: "CJC-1295 with DAC for growth hormone pathway research",
    body: [
      "CJC-1295 with Drug Affinity Complex (DAC) is a synthetic GHRH analogue studied in laboratory settings for extended receptor interaction profiles relative to shorter GHRH fragments. Peptide Protocol supplies this material as a lyophilised powder for controlled research use.",
      "Identity and purity are assessed by RP-HPLC, with Certificates of Analysis available for verified lots so intake records stay complete.",
    ],
    researchNotice: RESEARCH_NOTICE,
    specs: [
      { label: "Synonyms", value: "CJC-1295 DAC, CJC-1295 with Drug Affinity Complex" },
      { label: "CAS number", value: "863288-34-0 (family reference; confirm on batch COA)" },
      { label: "Chemical formula", value: "C165H269N47O46 (typical literature value)" },
      { label: "Molecular weight", value: "Approx. 3647 g/mol (as per batch COA)" },
      { label: "Form", value: "White to off-white lyophilised powder" },
      { label: "Purity", value: "≥99.0% (COA validated)" },
      { label: "Solubility", value: "Soluble in sterile research solvents as per lab protocol" },
      { label: "Quality checks", value: "RP-HPLC identity/purity assessment; third-party verification where listed" },
      { label: "Net content", value: "5mg per vial" },
    ],
    storage: [
      "Store dry at 2–8°C unless your batch documentation states otherwise.",
      "Protect from moisture, light, and repeated temperature cycling.",
      "Reconstitute only under trained laboratory procedures using suitable sterile solvents.",
      "Follow your organisation’s SOPs for labelling, use, and disposal.",
    ],
    included: [
      "1 × CJC-1295 with DAC, 5mg lyophilised vial",
      "Protective inner packing",
      "Access to batch-specific COA where available",
      "Australia Post tracking after dispatch",
    ],
    qualitySignals: [
      "≥99% purity target with COA support",
      "Third-party laboratory verification on listed batches",
      "Tamper-evident packing checks before dispatch",
    ],
    faqs: commonFaqs("CJC-1295 with DAC"),
    disclaimer: PRODUCT_DISCLAIMER,
    image: "/images/products/cjc-1295-dac.jpg",
  },
  {
    slug: "cjc-1295-no-dac-10mg",
    name: "CJC-1295 without DAC (10mg)",
    shortName: "CJC-1295 No DAC",
    strength: "10mg",
    priceAud: 99.99,
    categorySlugs: ["growth-hormone"],
    shortLabel: "Modified GRF (1-29) | Research grade | Lyophilised powder",
    metaTitle: "CJC-1295 No DAC 10mg Research Peptide Australia | Peptide Protocol",
    metaDescription:
      "Buy CJC-1295 without DAC (Mod GRF 1-29) 10mg lyophilised research peptide in Australia. Specs, storage notes, and COA access. Research use only.",
    headline: "CJC-1295 without DAC for controlled laboratory research",
    body: [
      "CJC-1295 without DAC, also called Modified GRF (1-29), is a synthetic 29-amino-acid analogue of growth hormone-releasing hormone (GHRH). Peptide Protocol supplies this material as a lyophilised powder for in vitro and other controlled research applications.",
      "Each batch is prepared for research inventory use, with purity assessed by RP-HPLC and a Certificate of Analysis available for verified lots.",
    ],
    researchNotice: RESEARCH_NOTICE,
    specs: [
      { label: "Synonyms", value: "Mod GRF (1-29), tetrasubstituted GRF (1-29)" },
      { label: "CAS number", value: "863288-34-0" },
      { label: "Chemical formula", value: "C152H252N44O42" },
      { label: "Molecular weight", value: "Approx. 3367.9 g/mol" },
      { label: "Peptide length", value: "29 amino acids" },
      { label: "Form", value: "White to off-white lyophilised powder" },
      { label: "Purity", value: "≥99.0% (COA validated)" },
      { label: "Solubility", value: "Soluble in sterile research solvents as per lab protocol" },
      { label: "Quality checks", value: "RP-HPLC identity/purity assessment; third-party verification where listed" },
      { label: "Net content", value: "10mg per vial" },
    ],
    storage: [
      "Store dry at 2–8°C unless your batch documentation states otherwise.",
      "Protect from moisture, light, and repeated temperature cycling.",
      "Reconstitute only under trained laboratory procedures using suitable sterile solvents.",
      "Follow your organisation’s SOPs for labelling, use, and disposal.",
      "Do not use outside a controlled research setting.",
    ],
    included: [
      "1 × CJC-1295 without DAC, 10mg lyophilised vial",
      "Protective inner packing",
      "Access to batch-specific COA where available",
      "Australia Post tracking after dispatch",
    ],
    qualitySignals: [
      "≥99% purity target with COA support",
      "Third-party laboratory verification on listed batches",
      "Tamper-evident packing checks before dispatch",
      "Clear product labelling for research inventory control",
    ],
    faqs: commonFaqs("CJC-1295 without DAC"),
    disclaimer: PRODUCT_DISCLAIMER,
    image: "/images/products/cjc-1295-no-dac.jpg",
    featured: true,
  },
  {
    slug: "dsip-5mg",
    name: "DSIP (5mg)",
    shortName: "DSIP",
    strength: "5mg",
    priceAud: 79.99,
    categorySlugs: ["cognitive-neurological"],
    shortLabel: "Delta sleep-inducing peptide | Research grade | Lyophilised powder",
    metaTitle: "DSIP 5mg Research Peptide Australia | Peptide Protocol",
    metaDescription:
      "Buy DSIP 5mg lyophilised research peptide in Australia. Specs, storage notes, and COA access. Research use only.",
    headline: "DSIP for sleep-related and neurological research settings",
    body: [
      "Delta sleep-inducing peptide (DSIP) is a nonapeptide studied in neurobiology and sleep-related research literature. Peptide Protocol supplies DSIP as a lyophilised powder for laboratory inventory and controlled experimental work.",
      "Batch purity is assessed by RP-HPLC, with documentation available so research teams can file identity and assay records.",
    ],
    researchNotice: RESEARCH_NOTICE,
    specs: [
      { label: "Synonyms", value: "Delta sleep-inducing peptide" },
      { label: "CAS number", value: "62568-57-4" },
      { label: "Chemical formula", value: "C35H48N10O15" },
      { label: "Molecular weight", value: "Approx. 848.8 g/mol" },
      { label: "Peptide length", value: "9 amino acids" },
      { label: "Form", value: "White to off-white lyophilised powder" },
      { label: "Purity", value: "≥99.0% (COA validated)" },
      { label: "Solubility", value: "Soluble in sterile research solvents as per lab protocol" },
      { label: "Quality checks", value: "RP-HPLC identity/purity assessment; third-party verification where listed" },
      { label: "Net content", value: "5mg per vial" },
    ],
    storage: [
      "Store dry at 2–8°C unless your batch documentation states otherwise.",
      "Protect from moisture, light, and repeated temperature cycling.",
      "Reconstitute only under trained laboratory procedures using suitable sterile solvents.",
      "Follow your organisation’s SOPs for labelling, use, and disposal.",
    ],
    included: [
      "1 × DSIP, 5mg lyophilised vial",
      "Protective inner packing",
      "Access to batch-specific COA where available",
      "Australia Post tracking after dispatch",
    ],
    qualitySignals: [
      "≥99% purity target with COA support",
      "Third-party laboratory verification on listed batches",
      "Clear product labelling for research inventory control",
    ],
    faqs: commonFaqs("DSIP"),
    disclaimer: PRODUCT_DISCLAIMER,
    image: "/images/products/dsip.jpg",
  },
  {
    slug: "epitalon-10mg",
    name: "Epitalon (10mg)",
    shortName: "Epitalon",
    strength: "10mg",
    priceAud: 88.95,
    categorySlugs: ["cognitive-neurological"],
    shortLabel: "Ala-Glu-Asp-Gly tetrapeptide | Research grade | Lyophilised powder",
    metaTitle: "Epitalon 10mg Research Peptide Australia | Peptide Protocol",
    metaDescription:
      "Buy Epitalon 10mg lyophilised research peptide in Australia. Specs, storage notes, and COA access. Research use only.",
    headline: "Epitalon for cellular ageing and pineal research models",
    body: [
      "Epitalon is a synthetic tetrapeptide (Ala-Glu-Asp-Gly) examined in laboratory literature related to cellular ageing pathways and pineal research models. Peptide Protocol supplies Epitalon as a lyophilised powder for controlled research applications.",
      "Lots are assessed for purity and identity, with Certificates of Analysis available for verified batches.",
    ],
    researchNotice: RESEARCH_NOTICE,
    specs: [
      { label: "Synonyms", value: "Epithalon, Ala-Glu-Asp-Gly" },
      { label: "CAS number", value: "307297-39-8" },
      { label: "Chemical formula", value: "C14H22N4O9" },
      { label: "Molecular weight", value: "Approx. 390.35 g/mol" },
      { label: "Peptide length", value: "4 amino acids" },
      { label: "Form", value: "White to off-white lyophilised powder" },
      { label: "Purity", value: "≥99.0% (COA validated)" },
      { label: "Solubility", value: "Soluble in sterile research solvents as per lab protocol" },
      { label: "Quality checks", value: "RP-HPLC identity/purity assessment; third-party verification where listed" },
      { label: "Net content", value: "10mg per vial" },
    ],
    storage: [
      "Store dry at 2–8°C unless your batch documentation states otherwise.",
      "Protect from moisture, light, and repeated temperature cycling.",
      "Reconstitute only under trained laboratory procedures using suitable sterile solvents.",
      "Follow your organisation’s SOPs for labelling, use, and disposal.",
    ],
    included: [
      "1 × Epitalon, 10mg lyophilised vial",
      "Protective inner packing",
      "Access to batch-specific COA where available",
      "Australia Post tracking after dispatch",
    ],
    qualitySignals: [
      "≥99% purity target with COA support",
      "Third-party laboratory verification on listed batches",
      "Tamper-evident packing checks before dispatch",
    ],
    faqs: commonFaqs("Epitalon"),
    disclaimer: PRODUCT_DISCLAIMER,
    image: "/images/products/epitalon.jpg",
  },
  {
    slug: "ghk-cu-100mg",
    name: "GHK-Cu (100mg)",
    shortName: "GHK-Cu",
    strength: "100mg",
    priceAud: 78.95,
    categorySlugs: ["cellular-mitochondrial"],
    shortLabel: "Copper tripeptide complex | Research grade | Lyophilised powder",
    metaTitle: "GHK-Cu 100mg Research Peptide Australia | Peptide Protocol",
    metaDescription:
      "Buy GHK-Cu 100mg lyophilised research peptide in Australia. Specs, storage notes, and COA access. Research use only.",
    headline: "GHK-Cu for cellular signalling and copper-peptide research",
    body: [
      "GHK-Cu is the copper(II) complex of the tripeptide glycyl-L-histidyl-L-lysine, studied in cellular signalling, extracellular matrix, and related laboratory models. Peptide Protocol supplies GHK-Cu as a lyophilised research material.",
      "Purity and identity documentation are available for verified lots so laboratory intake remains auditable.",
    ],
    researchNotice: RESEARCH_NOTICE,
    specs: [
      { label: "Synonyms", value: "Copper tripeptide-1, GHK copper complex" },
      { label: "CAS number", value: "89030-95-5 (confirm on batch COA)" },
      { label: "Chemical formula", value: "C14H24CuN6O4 (typical complex notation)" },
      { label: "Molecular weight", value: "Approx. 403.9 g/mol (as per batch COA)" },
      { label: "Peptide length", value: "3 amino acids (complexed with Cu2+)" },
      { label: "Form", value: "Blue to blue-green lyophilised powder (typical)" },
      { label: "Purity", value: "≥99.0% (COA validated)" },
      { label: "Solubility", value: "Soluble in sterile research solvents as per lab protocol" },
      { label: "Quality checks", value: "RP-HPLC / identity assessment as listed on COA" },
      { label: "Net content", value: "100mg per vial" },
    ],
    storage: [
      "Store dry at 2–8°C unless your batch documentation states otherwise.",
      "Protect from moisture, light, and repeated temperature cycling.",
      "Reconstitute only under trained laboratory procedures using suitable sterile solvents.",
      "Follow your organisation’s SOPs for labelling, use, and disposal.",
    ],
    included: [
      "1 × GHK-Cu, 100mg lyophilised vial",
      "Protective inner packing",
      "Access to batch-specific COA where available",
      "Australia Post tracking after dispatch",
    ],
    qualitySignals: [
      "≥99% purity target with COA support",
      "Third-party laboratory verification on listed batches",
      "Clear product labelling for research inventory control",
    ],
    faqs: commonFaqs("GHK-Cu"),
    disclaimer: PRODUCT_DISCLAIMER,
    image: "/images/products/ghk-cu.jpg",
  },
  {
    slug: "hcg-5000iu",
    name: "HCG (5000 IU)",
    shortName: "HCG",
    strength: "5000 IU",
    priceAud: 90.0,
    categorySlugs: ["other-compounds"],
    shortLabel: "Human chorionic gonadotropin | Research grade | Lyophilised",
    metaTitle: "HCG 5000 IU Research Material Australia | Peptide Protocol",
    metaDescription:
      "Buy HCG 5000 IU lyophilised research material in Australia. Specs, storage notes, and COA access. Research use only.",
    headline: "HCG for endocrine pathway research applications",
    body: [
      "Human chorionic gonadotropin (HCG) is a glycoprotein hormone supplied here strictly as a research material for laboratory endocrine and assay-related work. Peptide Protocol provides lyophilised HCG for controlled research inventory only.",
      "Batch documentation is available for verified lots. Confirm potency units and handling notes on the Certificate of Analysis before use in protocols.",
    ],
    researchNotice: RESEARCH_NOTICE,
    specs: [
      { label: "Synonyms", value: "Human chorionic gonadotropin, hCG" },
      { label: "Form", value: "Lyophilised powder" },
      { label: "Potency", value: "5000 IU per vial (as labelled; confirm on batch COA)" },
      { label: "Purity / identity", value: "As per batch COA" },
      { label: "Solubility", value: "Soluble in sterile research solvents as per lab protocol" },
      { label: "Quality checks", value: "Identity and potency as listed on batch documentation" },
      { label: "Net content", value: "5000 IU per vial" },
    ],
    storage: [
      "Store dry refrigerated as stated on batch documentation (typically 2–8°C).",
      "Protect from moisture, light, and repeated temperature cycling.",
      "Reconstitute only under trained laboratory procedures.",
      "Follow your organisation’s SOPs for labelling, use, and disposal.",
    ],
    included: [
      "1 × HCG, 5000 IU lyophilised vial",
      "Protective inner packing",
      "Access to batch-specific COA where available",
      "Australia Post tracking after dispatch",
    ],
    qualitySignals: [
      "Batch documentation available on request",
      "Clear labelling for research inventory control",
      "Tamper-evident packing checks before dispatch",
    ],
    faqs: commonFaqs("HCG"),
    disclaimer: PRODUCT_DISCLAIMER,
    image: "/images/products/hcg.jpg",
  },
  {
    slug: "ipamorelin-10mg",
    name: "Ipamorelin (10mg)",
    shortName: "Ipamorelin",
    strength: "10mg",
    priceAud: 60.0,
    categorySlugs: ["growth-hormone"],
    shortLabel: "Ghrelin mimetic pentapeptide | Research grade | Lyophilised powder",
    metaTitle: "Ipamorelin 10mg Research Peptide Australia | Peptide Protocol",
    metaDescription:
      "Buy Ipamorelin 10mg lyophilised research peptide in Australia. Specs, storage notes, and COA access. Research use only.",
    headline: "Ipamorelin for growth hormone secretagogue research",
    body: [
      "Ipamorelin is a synthetic pentapeptide studied as a selective growth hormone secretagogue in laboratory literature. Peptide Protocol supplies Ipamorelin as a lyophilised powder for in vitro and other controlled research applications.",
      "Each verified lot includes access to purity documentation so research teams can maintain complete inventory records.",
    ],
    researchNotice: RESEARCH_NOTICE,
    specs: [
      { label: "Synonyms", value: "NNC 26-0161 (literature reference)" },
      { label: "CAS number", value: "170851-70-4" },
      { label: "Chemical formula", value: "C38H49N9O5" },
      { label: "Molecular weight", value: "Approx. 711.9 g/mol" },
      { label: "Peptide length", value: "5 amino acids" },
      { label: "Form", value: "White to off-white lyophilised powder" },
      { label: "Purity", value: "≥99.0% (COA validated)" },
      { label: "Solubility", value: "Soluble in sterile research solvents as per lab protocol" },
      { label: "Quality checks", value: "RP-HPLC identity/purity assessment; third-party verification where listed" },
      { label: "Net content", value: "10mg per vial" },
    ],
    storage: [
      "Store dry at 2–8°C unless your batch documentation states otherwise.",
      "Protect from moisture, light, and repeated temperature cycling.",
      "Reconstitute only under trained laboratory procedures using suitable sterile solvents.",
      "Follow your organisation’s SOPs for labelling, use, and disposal.",
    ],
    included: [
      "1 × Ipamorelin, 10mg lyophilised vial",
      "Protective inner packing",
      "Access to batch-specific COA where available",
      "Australia Post tracking after dispatch",
    ],
    qualitySignals: [
      "≥99% purity target with COA support",
      "Third-party laboratory verification on listed batches",
      "Clear product labelling for research inventory control",
    ],
    faqs: commonFaqs("Ipamorelin"),
    disclaimer: PRODUCT_DISCLAIMER,
    image: "/images/products/ipamorelin.jpg",
    featured: true,
  },
  {
    slug: "melanotan-ii-10mg",
    name: "Melanotan II (10mg)",
    shortName: "Melanotan II",
    strength: "10mg",
    priceAud: 78.95,
    categorySlugs: ["other-compounds"],
    shortLabel: "Alpha-MSH analogue | Research grade | Lyophilised powder",
    metaTitle: "Melanotan II 10mg Research Peptide Australia | Peptide Protocol",
    metaDescription:
      "Buy Melanotan II 10mg lyophilised research peptide in Australia. Specs, storage notes, and COA access. Research use only.",
    headline: "Melanotan II for melanocortin pathway research",
    body: [
      "Melanotan II is a synthetic cyclic heptapeptide analogue of alpha-melanocyte-stimulating hormone, used in laboratory studies of melanocortin receptors and related pathways. Peptide Protocol supplies Melanotan II as a lyophilised research material.",
      "This catalogue listing is for research inventory only. It is not offered as a tanning, cosmetic, or consumer product.",
    ],
    researchNotice: RESEARCH_NOTICE,
    specs: [
      { label: "Synonyms", value: "MT-II, Melanotan 2" },
      { label: "CAS number", value: "121062-08-6" },
      { label: "Chemical formula", value: "C50H69N15O9" },
      { label: "Molecular weight", value: "Approx. 1024.2 g/mol" },
      { label: "Form", value: "White to off-white lyophilised powder" },
      { label: "Purity", value: "≥99.0% (COA validated)" },
      { label: "Solubility", value: "Soluble in sterile research solvents as per lab protocol" },
      { label: "Quality checks", value: "RP-HPLC identity/purity assessment; third-party verification where listed" },
      { label: "Net content", value: "10mg per vial" },
    ],
    storage: [
      "Store dry at 2–8°C unless your batch documentation states otherwise.",
      "Protect from moisture, light, and repeated temperature cycling.",
      "Reconstitute only under trained laboratory procedures using suitable sterile solvents.",
      "Follow your organisation’s SOPs for labelling, use, and disposal.",
    ],
    included: [
      "1 × Melanotan II, 10mg lyophilised vial",
      "Protective inner packing",
      "Access to batch-specific COA where available",
      "Australia Post tracking after dispatch",
    ],
    qualitySignals: [
      "≥99% purity target with COA support",
      "Third-party laboratory verification on listed batches",
      "Tamper-evident packing checks before dispatch",
    ],
    faqs: commonFaqs("Melanotan II"),
    disclaimer: PRODUCT_DISCLAIMER,
    image: "/images/products/melanotan-ii.jpg",
  },
  {
    slug: "mots-c-10mg",
    name: "MOTS-c (10mg)",
    shortName: "MOTS-c",
    strength: "10mg",
    priceAud: 88.95,
    categorySlugs: ["cellular-mitochondrial"],
    shortLabel: "Mitochondrial-derived peptide | Research grade | Lyophilised powder",
    metaTitle: "MOTS-c 10mg Research Peptide Australia | Peptide Protocol",
    metaDescription:
      "Buy MOTS-c 10mg lyophilised research peptide in Australia. Specs, storage notes, and COA access. Research use only.",
    headline: "MOTS-c for mitochondrial and metabolic pathway research",
    body: [
      "MOTS-c is a mitochondrial open reading frame-encoded peptide studied in cellular energy and metabolic pathway research. Peptide Protocol supplies MOTS-c as a lyophilised powder for controlled laboratory applications.",
      "Verified lots include purity assessment by RP-HPLC and Certificate of Analysis access for research record-keeping.",
    ],
    researchNotice: RESEARCH_NOTICE,
    specs: [
      { label: "Synonyms", value: "Mitochondrial open reading frame of the 12S rRNA type-c" },
      { label: "CAS number", value: "1627580-64-6 (confirm on batch COA)" },
      { label: "Chemical formula", value: "C101H152N28O22 (typical literature value)" },
      { label: "Molecular weight", value: "Approx. 2174.6 g/mol (as per batch COA)" },
      { label: "Peptide length", value: "16 amino acids" },
      { label: "Form", value: "White to off-white lyophilised powder" },
      { label: "Purity", value: "≥99.0% (COA validated)" },
      { label: "Solubility", value: "Soluble in sterile research solvents as per lab protocol" },
      { label: "Quality checks", value: "RP-HPLC identity/purity assessment; third-party verification where listed" },
      { label: "Net content", value: "10mg per vial" },
    ],
    storage: [
      "Store dry at 2–8°C unless your batch documentation states otherwise.",
      "Protect from moisture, light, and repeated temperature cycling.",
      "Reconstitute only under trained laboratory procedures using suitable sterile solvents.",
      "Follow your organisation’s SOPs for labelling, use, and disposal.",
    ],
    included: [
      "1 × MOTS-c, 10mg lyophilised vial",
      "Protective inner packing",
      "Access to batch-specific COA where available",
      "Australia Post tracking after dispatch",
    ],
    qualitySignals: [
      "≥99% purity target with COA support",
      "Third-party laboratory verification on listed batches",
      "Clear product labelling for research inventory control",
    ],
    faqs: commonFaqs("MOTS-c"),
    disclaimer: PRODUCT_DISCLAIMER,
    image: "/images/products/mots-c.jpg",
  },
  {
    slug: "retatrutide-10mg",
    name: "Retatrutide (10mg)",
    shortName: "Retatrutide",
    strength: "10mg",
    priceAud: 129.99,
    categorySlugs: ["metabolic"],
    shortLabel: "Triple agonist research peptide | Research grade | Lyophilised powder",
    metaTitle: "Retatrutide 10mg Research Peptide Australia | Peptide Protocol",
    metaDescription:
      "Buy Retatrutide 10mg lyophilised research peptide in Australia. Specs, storage notes, and COA access. Research use only.",
    headline: "Retatrutide for multi-agonist metabolic research models",
    body: [
      "Retatrutide is a synthetic peptide studied as a multi-agonist research compound in metabolic pathway literature. Peptide Protocol supplies Retatrutide as a lyophilised powder strictly for laboratory and in vitro research.",
      "Identity and purity are documented on Certificates of Analysis for verified lots. Confirm exact molecular parameters on your batch COA before protocol use.",
    ],
    researchNotice: RESEARCH_NOTICE,
    specs: [
      { label: "Synonyms", value: "LY3437943 (literature reference)" },
      { label: "CAS number", value: "2381089-83-2 (confirm on batch COA)" },
      { label: "Molecular weight", value: "Approx. 4731 g/mol (as per batch COA)" },
      { label: "Form", value: "White to off-white lyophilised powder" },
      { label: "Purity", value: "≥99.0% (COA validated)" },
      { label: "Solubility", value: "Soluble in sterile research solvents as per lab protocol" },
      { label: "Quality checks", value: "RP-HPLC identity/purity assessment; third-party verification where listed" },
      { label: "Net content", value: "10mg per vial" },
    ],
    storage: [
      "Store dry at 2–8°C unless your batch documentation states otherwise.",
      "Protect from moisture, light, and repeated temperature cycling.",
      "Reconstitute only under trained laboratory procedures using suitable sterile solvents.",
      "Follow your organisation’s SOPs for labelling, use, and disposal.",
    ],
    included: [
      "1 × Retatrutide, 10mg lyophilised vial",
      "Protective inner packing",
      "Access to batch-specific COA where available",
      "Australia Post tracking after dispatch",
    ],
    qualitySignals: [
      "≥99% purity target with COA support",
      "Third-party laboratory verification on listed batches",
      "Tamper-evident packing checks before dispatch",
    ],
    faqs: commonFaqs("Retatrutide"),
    disclaimer: PRODUCT_DISCLAIMER,
    image: "/images/products/retatrutide.jpg",
    featured: true,
  },
  {
    slug: "semax-11mg",
    name: "Semax (11mg)",
    shortName: "Semax",
    strength: "11mg",
    priceAud: 59.99,
    categorySlugs: ["cognitive-neurological"],
    shortLabel: "ACTH (4-10) analogue | Research grade | Lyophilised powder",
    metaTitle: "Semax 11mg Research Peptide Australia | Peptide Protocol",
    metaDescription:
      "Buy Semax 11mg lyophilised research peptide in Australia. Specs, storage notes, and COA access. Research use only.",
    headline: "Semax for cognitive and neurological research models",
    body: [
      "Semax is a synthetic heptapeptide analogue related to ACTH (4-10), examined in neurobiology research settings. Peptide Protocol supplies Semax as a lyophilised powder for controlled laboratory use.",
      "Batch purity is assessed with RP-HPLC, and Certificates of Analysis are available for verified lots.",
    ],
    researchNotice: RESEARCH_NOTICE,
    specs: [
      { label: "Synonyms", value: "Met-Glu-His-Phe-Pro-Gly-Pro" },
      { label: "CAS number", value: "80714-61-0" },
      { label: "Chemical formula", value: "C37H51N9O10S" },
      { label: "Molecular weight", value: "Approx. 813.9 g/mol" },
      { label: "Peptide length", value: "7 amino acids" },
      { label: "Form", value: "White to off-white lyophilised powder" },
      { label: "Purity", value: "≥99.0% (COA validated)" },
      { label: "Solubility", value: "Soluble in sterile research solvents as per lab protocol" },
      { label: "Quality checks", value: "RP-HPLC identity/purity assessment; third-party verification where listed" },
      { label: "Net content", value: "11mg per vial" },
    ],
    storage: [
      "Store dry at 2–8°C unless your batch documentation states otherwise.",
      "Protect from moisture, light, and repeated temperature cycling.",
      "Reconstitute only under trained laboratory procedures using suitable sterile solvents.",
      "Follow your organisation’s SOPs for labelling, use, and disposal.",
    ],
    included: [
      "1 × Semax, 11mg lyophilised vial",
      "Protective inner packing",
      "Access to batch-specific COA where available",
      "Australia Post tracking after dispatch",
    ],
    qualitySignals: [
      "≥99% purity target with COA support",
      "Third-party laboratory verification on listed batches",
      "Clear product labelling for research inventory control",
    ],
    faqs: commonFaqs("Semax"),
    disclaimer: PRODUCT_DISCLAIMER,
    image: "/images/products/semax.jpg",
  },
  {
    slug: "sermorelin-10mg",
    name: "Sermorelin (10mg)",
    shortName: "Sermorelin",
    strength: "10mg",
    priceAud: 79.99,
    categorySlugs: ["growth-hormone"],
    shortLabel: "GHRH (1-29) amide | Research grade | Lyophilised powder",
    metaTitle: "Sermorelin 10mg Research Peptide Australia | Peptide Protocol",
    metaDescription:
      "Buy Sermorelin 10mg lyophilised research peptide in Australia. Specs, storage notes, and COA access. Research use only.",
    headline: "Sermorelin for GHRH pathway laboratory research",
    body: [
      "Sermorelin is a synthetic 29-amino-acid amidated fragment corresponding to GHRH (1-29), used in growth hormone pathway research. Peptide Protocol supplies Sermorelin as a lyophilised powder for laboratory applications only.",
      "Purity and identity are documented for verified lots so research teams can maintain complete material records.",
    ],
    researchNotice: RESEARCH_NOTICE,
    specs: [
      { label: "Synonyms", value: "GHRH (1-29) amide, GRF 1-29" },
      { label: "CAS number", value: "86168-78-7" },
      { label: "Chemical formula", value: "C149H246N44O42S" },
      { label: "Molecular weight", value: "Approx. 3357.9 g/mol" },
      { label: "Peptide length", value: "29 amino acids" },
      { label: "Form", value: "White to off-white lyophilised powder" },
      { label: "Purity", value: "≥99.0% (COA validated)" },
      { label: "Solubility", value: "Soluble in sterile research solvents as per lab protocol" },
      { label: "Quality checks", value: "RP-HPLC identity/purity assessment; third-party verification where listed" },
      { label: "Net content", value: "10mg per vial" },
    ],
    storage: [
      "Store dry at 2–8°C unless your batch documentation states otherwise.",
      "Protect from moisture, light, and repeated temperature cycling.",
      "Reconstitute only under trained laboratory procedures using suitable sterile solvents.",
      "Follow your organisation’s SOPs for labelling, use, and disposal.",
    ],
    included: [
      "1 × Sermorelin, 10mg lyophilised vial",
      "Protective inner packing",
      "Access to batch-specific COA where available",
      "Australia Post tracking after dispatch",
    ],
    qualitySignals: [
      "≥99% purity target with COA support",
      "Third-party laboratory verification on listed batches",
      "Tamper-evident packing checks before dispatch",
    ],
    faqs: commonFaqs("Sermorelin"),
    disclaimer: PRODUCT_DISCLAIMER,
    image: "/images/products/sermorelin.jpg",
  },
  {
    slug: "tb-500-10mg",
    name: "TB-500 (10mg)",
    shortName: "TB-500",
    strength: "10mg",
    priceAud: 118.95,
    categorySlugs: ["tissue-recovery"],
    shortLabel: "Thymosin Beta-4 fragment research material | Lyophilised powder",
    metaTitle: "TB-500 10mg Research Peptide Australia | Peptide Protocol",
    metaDescription:
      "Buy TB-500 10mg lyophilised research peptide in Australia. Specs, storage notes, and COA access. Research use only.",
    headline: "TB-500 for tissue and cytoskeletal research models",
    body: [
      "TB-500 refers to research material related to the active region of thymosin beta-4, studied in cytoskeletal organisation and tissue-model laboratory work. Peptide Protocol supplies TB-500 as a lyophilised powder for controlled research use.",
      "Confirm exact sequence and molecular details on your batch Certificate of Analysis before incorporating the material into protocols.",
    ],
    researchNotice: RESEARCH_NOTICE,
    specs: [
      { label: "Synonyms", value: "Thymosin Beta-4 fragment research material, TB500" },
      { label: "CAS number", value: "As per batch COA (thymosin β4 family references vary)" },
      { label: "Molecular weight", value: "As per batch COA" },
      { label: "Form", value: "White to off-white lyophilised powder" },
      { label: "Purity", value: "≥99.0% (COA validated)" },
      { label: "Solubility", value: "Soluble in sterile research solvents as per lab protocol" },
      { label: "Quality checks", value: "RP-HPLC identity/purity assessment; third-party verification where listed" },
      { label: "Net content", value: "10mg per vial" },
    ],
    storage: [
      "Store dry at 2–8°C unless your batch documentation states otherwise.",
      "Protect from moisture, light, and repeated temperature cycling.",
      "Reconstitute only under trained laboratory procedures using suitable sterile solvents.",
      "Follow your organisation’s SOPs for labelling, use, and disposal.",
    ],
    included: [
      "1 × TB-500, 10mg lyophilised vial",
      "Protective inner packing",
      "Access to batch-specific COA where available",
      "Australia Post tracking after dispatch",
    ],
    qualitySignals: [
      "≥99% purity target with COA support",
      "Third-party laboratory verification on listed batches",
      "Clear product labelling for research inventory control",
    ],
    faqs: commonFaqs("TB-500"),
    disclaimer: PRODUCT_DISCLAIMER,
    image: "/images/products/tb-500.jpg",
  },
  {
    slug: "tesamorelin-10mg",
    name: "Tesamorelin (10mg)",
    shortName: "Tesamorelin",
    strength: "10mg",
    priceAud: 119.99,
    categorySlugs: ["growth-hormone"],
    shortLabel: "Stabilised GHRH analogue | Research grade | Lyophilised powder",
    metaTitle: "Tesamorelin 10mg Research Peptide Australia | Peptide Protocol",
    metaDescription:
      "Buy Tesamorelin 10mg lyophilised research peptide in Australia. Specs, storage notes, and COA access. Research use only.",
    headline: "Tesamorelin for GHRH analogue laboratory research",
    body: [
      "Tesamorelin is a synthetic stabilised analogue of growth hormone-releasing hormone used in laboratory research on GHRH pathways. Peptide Protocol supplies Tesamorelin as a lyophilised powder for research inventory only.",
      "Verified lots include purity documentation. Always cross-check molecular parameters against the batch COA.",
    ],
    researchNotice: RESEARCH_NOTICE,
    specs: [
      { label: "Synonyms", value: "TH9507 (literature reference)" },
      { label: "CAS number", value: "218949-48-5" },
      { label: "Chemical formula", value: "C221H366N72O67S (typical literature value)" },
      { label: "Molecular weight", value: "Approx. 5135.9 g/mol (as per batch COA)" },
      { label: "Form", value: "White to off-white lyophilised powder" },
      { label: "Purity", value: "≥99.0% (COA validated)" },
      { label: "Solubility", value: "Soluble in sterile research solvents as per lab protocol" },
      { label: "Quality checks", value: "RP-HPLC identity/purity assessment; third-party verification where listed" },
      { label: "Net content", value: "10mg per vial" },
    ],
    storage: [
      "Store dry at 2–8°C unless your batch documentation states otherwise.",
      "Protect from moisture, light, and repeated temperature cycling.",
      "Reconstitute only under trained laboratory procedures using suitable sterile solvents.",
      "Follow your organisation’s SOPs for labelling, use, and disposal.",
    ],
    included: [
      "1 × Tesamorelin, 10mg lyophilised vial",
      "Protective inner packing",
      "Access to batch-specific COA where available",
      "Australia Post tracking after dispatch",
    ],
    qualitySignals: [
      "≥99% purity target with COA support",
      "Third-party laboratory verification on listed batches",
      "Tamper-evident packing checks before dispatch",
    ],
    faqs: commonFaqs("Tesamorelin"),
    disclaimer: PRODUCT_DISCLAIMER,
    image: "/images/products/tesamorelin.jpg",
  },
  {
    slug: "tirzepatide-10mg",
    name: "Tirzepatide (10mg)",
    shortName: "Tirzepatide",
    strength: "10mg",
    priceAud: 139.99,
    categorySlugs: ["metabolic"],
    shortLabel: "Dual GIP/GLP-1 receptor agonist research peptide | Lyophilised powder",
    metaTitle: "Tirzepatide 10mg Research Peptide Australia | Peptide Protocol",
    metaDescription:
      "Buy Tirzepatide 10mg lyophilised research peptide in Australia. Specs, storage notes, and COA access. Research use only.",
    headline: "Tirzepatide for dual-agonist metabolic research",
    body: [
      "Tirzepatide is a synthetic dual glucose-dependent insulinotropic polypeptide (GIP) and glucagon-like peptide-1 (GLP-1) receptor agonist peptide studied in metabolic pathway research. Peptide Protocol supplies Tirzepatide as a lyophilised powder for laboratory use only.",
      "This material is not a medicine or consumer product. Confirm molecular and purity details on the batch Certificate of Analysis before protocol use.",
    ],
    researchNotice: RESEARCH_NOTICE,
    specs: [
      { label: "Synonyms", value: "LY3298176 (literature reference)" },
      { label: "CAS number", value: "2023788-19-2" },
      { label: "Chemical formula", value: "C225H348N48O68 (typical literature value)" },
      { label: "Molecular weight", value: "Approx. 4813 g/mol (as per batch COA)" },
      { label: "Form", value: "White to off-white lyophilised powder" },
      { label: "Purity", value: "≥99.0% (COA validated)" },
      { label: "Solubility", value: "Soluble in sterile research solvents as per lab protocol" },
      { label: "Quality checks", value: "RP-HPLC identity/purity assessment; third-party verification where listed" },
      { label: "Net content", value: "10mg per vial" },
    ],
    storage: [
      "Store dry at 2–8°C unless your batch documentation states otherwise.",
      "Protect from moisture, light, and repeated temperature cycling.",
      "Reconstitute only under trained laboratory procedures using suitable sterile solvents.",
      "Follow your organisation’s SOPs for labelling, use, and disposal.",
    ],
    included: [
      "1 × Tirzepatide, 10mg lyophilised vial",
      "Protective inner packing",
      "Access to batch-specific COA where available",
      "Australia Post tracking after dispatch",
    ],
    qualitySignals: [
      "≥99% purity target with COA support",
      "Third-party laboratory verification on listed batches",
      "Tamper-evident packing checks before dispatch",
    ],
    faqs: commonFaqs("Tirzepatide"),
    disclaimer: PRODUCT_DISCLAIMER,
    image: "/images/products/tirzepatide.jpg",
    featured: true,
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getProductsByCategory(categorySlug: string): Product[] {
  return products.filter((p) => p.categorySlugs.includes(categorySlug));
}

export function formatPrice(aud: number): string {
  return new Intl.NumberFormat("en-AU", {
    style: "currency",
    currency: "AUD",
  }).format(aud);
}
